name: flutter_challenge
description: Francesco La Forgia flutter challenge for Deliveristo
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_displaymode: ^0.6.0
  flutter_riverpod: ^2.4.4
  go_router: ^12.0.0
  dio: ^5.3.3
  slang: ^3.25.0
  json_annotation: ^4.8.1
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  slang_build_runner: ^3.25.0
  slang_flutter: ^3.25.0
  fast_i18n: ^5.12.6
  riverpod_generator: ^2.3.5

flutter:
  uses-material-design: true

  assets:
    - assets/lotties/